/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'MarkPerry' at '7/01/14 2:38 PM' with Gradle 1.9
 *
 * @author MarkPerry, @date 7/01/14 2:38 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
