/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'MarkPerry' at '7/01/14 2:38 PM' with Gradle 1.9
 *
 * @author MarkPerry, @date 7/01/14 2:38 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
